#include "cpprest/json_visit.h"

namespace web
{
    namespace json
    {
        namespace experimental
        {
            // sample stylesheet for the HTML generated by html_visitor
            const char* html_stylesheet = R"-stylesheet-(
.json
{
  font-family: monospace
}
.json .number, .json .boolean, .json .null
{
  color: blue
}
.json .string
{
  color: brown
}
.json .object
{
  color: grey
}
.json .array
{
  color: grey
}
.json ul, .json ol
{
  list-style: none;
  border-left: 0.5px dotted rgba(0, 128, 0, 0.25)
}
.json ul:empty, .json ol:empty
{
  display: none
}
.json .name
{
  color: purple
}
)-stylesheet-";
        }
    }
}
