- name: setup developer command prompt for Microsoft Visual C++
  if: runner.os == 'Windows'
  uses: ilammy/msvc-dev-cmd@v1

- name: build
  shell: bash
  run: |
    cmake -S "${{ env.GITHUB_WORKSPACE }}/Development" \
      -B "${{ env.RUNNER_WORKSPACE }}/build" \
      -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX="${{ env.RUNNER_WORKSPACE }}/install" \
      ${{ env.CMAKE_COMPILER_ARGS }} \
      ${{ env.CMAKE_EXTRA_ARGS }}
    cmake --build "${{ env.RUNNER_WORKSPACE }}/build"

- name: dump conan lockfile
  if: matrix.use_conan == true
  run: |
    cat ${{ env.RUNNER_WORKSPACE }}/build/conan.lock
