- name: install
  if: matrix.os != 'ubuntu-14.04'
  uses: lukka/run-cmake@v3.4
  with:
    cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
    cmakeListsTxtPath: '${{ env.GITHUB_WORKSPACE }}/Development/CMakeLists.txt'
    buildDirectory: '${{ env.RUNNER_WORKSPACE }}/build/'
    buildWithCMakeArgs: '--target install'
